=== xdrahosm/SIPVS_Project/resources/toSign/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns:md="http://www.example.org/sipvs"
		   targetNamespace="http://www.example.org/sipvs"
		   elementFormDefault="qualified">

	<xs:element name="Library">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element name="Book" type="md:book"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="book">
		<xs:sequence>
			<xs:element name="BookName" type="xs:string"/>
			<xs:element name="AuthorName" type="xs:string"/>
			<xs:element name="Pages" type="xs:integer"/>
			<xs:element name="PrintingYear" type="xs:integer"/>
			<xs:element name="FirstPublished" type="xs:integer"/>
			<xs:element name="ISBN" type="xs:string"/>
			<xs:element name="BookDescription" type="xs:string"/>
			<xs:element name="BorrowHistory" type="md:borrowHistory"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="borrowHistory">
		<xs:sequence minOccurs="1" maxOccurs="30">
			<xs:element name="Borrow" type="md:borrow"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="borrow">
		<xs:sequence>
			<xs:element name="StudentName" type="xs:string"/>
			<xs:element name="BorrowDate" type="xs:date"/>
			<xs:element name="ReturnDate" type="xs:date"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" use="required"/>
	</xs:complexType>

</xs:schema>

=== xdrahosm/SIPVS_Project/resources/xml/cviko.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><md:Library xmlns:md="http://www.example.org/sipvs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/sipvs/schema.xsd"><md:Book><md:BookName>name</md:BookName><md:AuthorName>author @_ AS &gt;&lt;$%#^&amp;</md:AuthorName><md:Pages>54</md:Pages><md:PrintingYear>1999</md:PrintingYear><md:FirstPublished>655</md:FirstPublished><md:ISBN>a156152</md:ISBN><md:BookDescription>description @#^$W 1385 }| ?</md:BookDescription><md:BorrowHistory><md:Borrow id="1"><md:StudentName>marek</md:StudentName><md:BorrowDate>2020-10-07</md:BorrowDate><md:ReturnDate>2020-10-08</md:ReturnDate></md:Borrow><md:Borrow id="2"><md:StudentName>marek1</md:StudentName><md:BorrowDate>2020-10-07</md:BorrowDate><md:ReturnDate>2020-10-08</md:ReturnDate></md:Borrow></md:BorrowHistory></md:Book></md:Library>

=== xdrahosm/SIPVS_Project/resources/toSign/sample.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<md:Library xmlns:md="http://www.example.org/sipvs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.example.org/sipvs/schema.xsd">
    <md:Book>
        <md:BookName>name</md:BookName>
        <md:AuthorName>author</md:AuthorName>
        <md:Pages>55</md:Pages>
        <md:PrintingYear>199</md:PrintingYear>
        <md:FirstPublished>159</md:FirstPublished>
        <md:ISBN>dfav</md:ISBN>
        <md:BookDescription>test description</md:BookDescription>
        <md:BorrowHistory>
            <md:Borrow id="1">
                <md:StudentName>test</md:StudentName>
                <md:BorrowDate>2020-10-08</md:BorrowDate>
                <md:ReturnDate>2020-10-10</md:ReturnDate>
            </md:Borrow>
            <md:Borrow id="2">
                <md:StudentName>test dva</md:StudentName>
                <md:BorrowDate>2020-10-11</md:BorrowDate>
                <md:ReturnDate>2020-10-13</md:ReturnDate>
            </md:Borrow>
        </md:BorrowHistory>
    </md:Book>
</md:Library>

=== xdrahosm/SIPVS_Project/resources/xml/novy1.xml
<?xml version="1.0" encoding="UTF-8"?><md:Library xmlns:md="http://www.example.org/sipvs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/sipvs/schema.xsd"><md:Book><md:BookName>Guliverove cety</md:BookName><md:AuthorName>Guliver</md:AuthorName><md:Pages>123</md:Pages><md:PrintingYear>111</md:PrintingYear><md:FirstPublished>111</md:FirstPublished><md:ISBN>212132</md:ISBN><md:BookDescription>aksjalsjaklsjdlaksjd	</md:BookDescription><md:BorrowHistory><md:Borrow id="1"><md:StudentName>Janko Hrasko</md:StudentName><md:BorrowDate>2020-10-01</md:BorrowDate><md:ReturnDate>2020-10-27</md:ReturnDate></md:Borrow></md:BorrowHistory></md:Book></md:Library>

=== xdrahosm/SIPVS_Project/resources/xml/export.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<md:Library xmlns:md="http://www.example.org/sipvs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.example.org/sipvs/schema.xsd">
    <md:Book>
        <md:BookName>test</md:BookName>
        <md:AuthorName>test</md:AuthorName>
        <md:Pages>78</md:Pages>
        <md:PrintingYear>858</md:PrintingYear>
        <md:FirstPublished>587</md:FirstPublished>
        <md:ISBN>ercd</md:ISBN>
        <md:BookDescription>vfdz</md:BookDescription>
        <md:BorrowHistory>
            <md:Borrow id="1">
                <md:StudentName>a</md:StudentName>
                <md:BorrowDate>2020-10-02</md:BorrowDate>
                <md:ReturnDate>2020-10-03</md:ReturnDate>
            </md:Borrow>
            <md:Borrow id="2">
                <md:StudentName>agf</md:StudentName>
                <md:BorrowDate>2020-09-29</md:BorrowDate>
                <md:ReturnDate>2020-10-03</md:ReturnDate>
            </md:Borrow>
            <md:Borrow id="3">
                <md:StudentName>agf</md:StudentName>
                <md:BorrowDate>2020-09-29</md:BorrowDate>
                <md:ReturnDate>2020-10-03</md:ReturnDate>
            </md:Borrow>
            <md:Borrow id="4">
                <md:StudentName>agf</md:StudentName>
                <md:BorrowDate>2020-09-29</md:BorrowDate>
                <md:ReturnDate>2020-10-28</md:ReturnDate>
            </md:Borrow>
        </md:BorrowHistory>
    </md:Book>
</md:Library>
